### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JanX2** [WangYun1995/FortranCWT#1]
Thank you for publishing this! 

What’s the source code license this is released under?

**Comment by WangYun1995** [comment]
Sorry, I don't know what is the 'source code license'.

**Comment by JanX2** [comment]
If I understand this correctly, you wrote the code in this repository. Did I get that right?

In that case, you can choose a license. Like the MIT license for example. 

This is so others, like me, know what they can and cannot do with the source code you published. 

Thank you putting your project out there by the way!

**Comment by WangYun1995** [comment]
Yes, I wrote the code and uploaded it to the Github

**Comment by JanX2** [comment]
[Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

You can also use [choosealicense.com](https://choosealicense.com).

**Comment by WangYun1995** [comment]
Ok, I have chosen the GPL-3.0 license.
